name: SSH Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'readme.md'

jobs:

  Continous-Integration:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setting up environment
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install flake8
      run: |
          pip install flake8 --no-cache
    - name: Checking code
      run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo TEST
          ls
            
  Continous-Deployment:
    runs-on: ubuntu-latest
    needs: Continous-Integration
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to EC2 instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: 3.110.131.85
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
            cd Company-work-environment-management
            git pull origin master
            sudo supervisorctl reload
            exit

