name: SSH Deploy

on:
  push:
    branches:
      - master

jobs:
  Continous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checking code
        run: |
          pip install flake8 --no-cache
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          echo TEST
            
  Continous-Deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to EC2 instance and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: 13.234.30.170
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls
            cd Company-work-environment-management
            git pull origin master
            sudo supervisorctl reload
            exit

